version: '3.8'

services:

  db:
    image: postgres
    container_name: testedb
    ports:
      - "5432:5432"
    tty: true
    volumes:
      - .docker/.pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=testedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=localhost
